version: "3.1"
services:

  web:
    image: node:alpine
    command: npm run test-watch
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./todo_api:/application
      - ./.env:/application/.env
    working_dir: /application
    restart: "no"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${DB_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASS}
