version: "3.1"
services:

  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    restart: "no"

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8091:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}

  web:
    image: node:alpine
    command: npm run test-watch
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./todo_api:/application
      - ./.env:/application/.env
      - ./.env_test:/application/.env_test
    working_dir: /application
    links:
      - mongo
    restart: "no"
