version: "3.1"
services:

  web:
    image: node:alpine
    command: npm run dev
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./todo_api:/application
      - ./.env:/application/.env
    working_dir: /application
    restart: "no"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DB}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASS}
