version: "3.1"
services:

  web:
    image: node:alpine
    command: npm run dev
    container_name: nodejs
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./webserver:/application
    working_dir: /application
    restart: "no"


networks:
  default:
    external:
      name: my-network